# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Layer 3 of the RIVET PR-CI watcher — responder.

The watcher (`pr_check_watcher.py`, slice 18) returns `StateFlip`
events. This module routes them to user-visible surfaces:

  - **infra** flips → high-urgency "ACTION REQUIRED" notification
    (operator must fix the underlying account/runner/billing issue;
    no fix branch helps)
  - **code** flips  → normal-urgency "FIX NEEDED" notification +
    a failure-report markdown file under
    ``~/.axi/agents/rivet/reports/`` with the failing job context
    and actionable next steps. The notification body points at the
    report path.
  - **recovery** flips → low-urgency "recovered" notification.

Conservative cut for v1: NO destructive ops. No auto-branch-spawn,
no auto-issue-close (auto-close on recovery is slice 20). A wrong
auto-commit on the user's branch is worse than the missed
notification we're trying to fix; better to surface and let
a human or downstream agent decide.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

from .pr_check_auto_closer import StaleIssue, auto_close_on_recovery
from .pr_check_watcher import StateFlip


class NotificationSink(Protocol):
    """Subset of the publishing `NotificationProvider` interface we
    actually use. Conformers: `TerminalNotificationProvider`, the
    test-only `FakeSink`."""

    def send(
        self,
        recipients: list[str],
        subject: str,
        body: str,
        urgency: str = "normal",
    ) -> bool:
        ...


@dataclass(frozen=True)
class FailureReport:
    """Where the failure-context markdown was written for a code flip."""

    path: Path
    pr_number: int


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------


def _render_report(flip: StateFlip) -> str:
    """Render the failure-context markdown for a code-flip.

    Sections:
      - PR header (number, title, URL, head branch)
      - Failing jobs (name, description, link)
      - Next steps (concrete suggestions a downstream agent or human
        can act on without reverse-engineering the responder)
    """
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append(f"# PR #{flip.pr_number} — CI fix needed")
    lines.append("")
    lines.append(f"_Generated by RIVET at {ts}._")
    lines.append("")
    lines.append(f"- **Title:** {flip.title}")
    lines.append(f"- **URL:** {flip.url}")
    lines.append(f"- **Branch:** `{flip.head_branch}`")
    lines.append(f"- **State:** {flip.from_state} → {flip.to_state}")
    lines.append(f"- **Classification:** {flip.classification}")
    lines.append("")
    lines.append("## Failing jobs")
    lines.append("")
    if flip.failing_rows:
        for row in flip.failing_rows:
            link = f" — {row.link}" if row.link else ""
            desc = row.description or "(no description)"
            lines.append(f"- **{row.name}**: {desc}{link}")
    else:
        lines.append("_(no per-job rows captured)_")
    lines.append("")
    lines.append("## Next steps")
    lines.append("")
    lines.append(
        "1. Open the failing job log(s) above and read the actual error."
    )
    lines.append(
        f"2. Reproduce locally: `git switch {flip.head_branch} && "
        "pytest -x` (or whichever job's command matches)."
    )
    lines.append(
        "3. Fix on the same branch and re-push; RIVET will detect "
        "the recovery flip on the next heartbeat tick."
    )
    lines.append(
        "4. If this is a flake (transient failure), re-run the job: "
        f"`gh run rerun --failed --repo <owner>/<repo>` for PR "
        f"#{flip.pr_number}'s latest run."
    )
    lines.append("")
    return "\n".join(lines)


def _reports_dir(state_dir: Path) -> Path:
    return state_dir / "agents" / "rivet" / "reports"


def _write_report(flip: StateFlip, state_dir: Path) -> FailureReport:
    reports_dir = _reports_dir(state_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    path = reports_dir / f"pr-{flip.pr_number}-{ts}.md"
    path.write_text(_render_report(flip), encoding="utf-8")
    return FailureReport(path=path, pr_number=flip.pr_number)


# ---------------------------------------------------------------------------
# Notification body composition
# ---------------------------------------------------------------------------


def _append_auto_closed_section(body: str, closed: list[StaleIssue]) -> str:
    """Tack an `Auto-closed:` block onto a recovery-notification body."""
    import os
    verb = "Would close (dry-run)" if os.environ.get(
        "RIVET_AUTO_CLOSE_DRY_RUN") == "1" else "Auto-closed"
    lines = [body, "", f"{verb}:"]
    for issue in closed:
        lines.append(f"  - #{issue.number}: {issue.title}")
    return "\n".join(lines)


def _compose_notification_body(
    flip: StateFlip, *, report_path: Path | None = None,
) -> str:
    lines: list[str] = [
        f"PR: {flip.title}",
        f"URL: {flip.url}",
        f"Branch: {flip.head_branch}",
        f"State: {flip.from_state} → {flip.to_state}",
        f"Classification: {flip.classification}",
        "",
    ]
    if flip.failing_rows:
        lines.append("Failing jobs:")
        for row in flip.failing_rows:
            desc = row.description or "(no description)"
            link = f"  {row.link}" if row.link else ""
            lines.append(f"  - {row.name}: {desc}{link}")
        lines.append("")
    if report_path is not None:
        lines.append(f"Report: {report_path}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def handle_flip(
    flip: StateFlip,
    *,
    state_dir: Path,
    sink: NotificationSink,
    bus: object = None,
) -> FailureReport | None:
    """Route one flip. Returns the FailureReport for code-failures;
    None for infra failures and recoveries.

    On a recovery (→ passing) emits the ``rivet.ci_recovered`` lifecycle
    event (ADR-046 signal half); ``bus`` is injectable for tests."""
    if flip.to_state == "failing":
        if flip.classification == "infra":
            sink.send(
                recipients=[],
                subject=f"[ACTION REQUIRED] PR #{flip.pr_number} — CI infra failure",
                body=_compose_notification_body(flip),
                urgency="high",
            )
            return None
        # code / unknown — write a report and surface
        report = _write_report(flip, state_dir=state_dir)
        sink.send(
            recipients=[],
            subject=f"[FIX NEEDED] PR #{flip.pr_number} — CI failure",
            body=_compose_notification_body(flip, report_path=report.path),
            urgency="normal",
        )
        return report

    if flip.to_state == "passing":
        # Best-effort auto-close any stale 🔴-CI-failed issues opened by
        # the github-actions bot for this PR. Defensive: see
        # pr_check_auto_closer for the safety filters and the dry-run /
        # hard-disable env vars.
        closed_issues = auto_close_on_recovery(flip)
        # Signal half (ADR-046): RIVET announces the recovery; TIDY and
        # other consumers subscribe. RIVET itself touches no git refs.
        from .lifecycle_events import CI_RECOVERED, emit

        emit(
            CI_RECOVERED,
            {"pr_number": flip.pr_number, "head_branch": flip.head_branch},
            bus=bus,
        )
        body = _compose_notification_body(flip)
        if closed_issues:
            body = _append_auto_closed_section(body, closed_issues)
        sink.send(
            recipients=[],
            subject=f"[recovered] PR #{flip.pr_number} — CI passing",
            body=body,
            urgency="low",
        )
        return None

    # pending / unknown — no responder action
    return None


def handle_flips(
    flips: list[StateFlip],
    *,
    state_dir: Path,
    sink: NotificationSink,
) -> list[FailureReport]:
    """Dispatch a batch of flips. Returns FailureReports for all
    code-failure flips in the batch (one per)."""
    out: list[FailureReport] = []
    for flip in flips:
        report = handle_flip(flip, state_dir=state_dir, sink=sink)
        if report is not None:
            out.append(report)
    return out
