# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Tests for `axiom.cli.schedule` (issue #203 — `axi schedule` primitive).

Today, agents that need recurring host-side work (heartbeats, doctor
sweeps, hygiene runs) historically dumped host-coupled scripts into
`scripts/` with hardcoded `$HOME/Projects/...` paths — a pattern
captured by the `check_scripts_with_hardcoded_paths` signal in
`hygiene.git_signals`.

`axi schedule create` writes a portable cron artifact to
`deploy/<host>/<name>.cron`, using `${REPO_DIR}` placeholders that
are substituted at install time by `axi schedule install`.
"""

from __future__ import annotations

from pathlib import Path

import pytest


@pytest.fixture
def project_root(tmp_path: Path) -> Path:
    root = tmp_path / "project"
    root.mkdir()
    (root / ".git").mkdir()
    return root


class TestCreateSchedule:
    def test_creates_file_at_deploy_host_name_cron(self, project_root):
        from axiom.cli.schedule import create_schedule
        out = create_schedule(
            project_root=project_root,
            name="mo-heartbeat",
            host="test-host",
            cron="*/15 * * * *",
            command="bash ${REPO_DIR}/scripts/mo-heartbeat.sh",
        )
        assert out == project_root / "deploy" / "test-host" / "mo-heartbeat.cron"
        assert out.is_file()

    def test_content_contains_cron_line(self, project_root):
        from axiom.cli.schedule import create_schedule
        out = create_schedule(
            project_root=project_root,
            name="mo-heartbeat",
            host="test-host",
            cron="*/15 * * * *",
            command="bash ${REPO_DIR}/scripts/mo-heartbeat.sh",
        )
        text = out.read_text()
        assert "*/15 * * * *" in text
        assert "${REPO_DIR}/scripts/mo-heartbeat.sh" in text

    def test_content_includes_provenance_header(self, project_root):
        """Header comment names the schedule + provenance so a reader of
        the deploy/ artifact knows where it came from."""
        from axiom.cli.schedule import create_schedule
        out = create_schedule(
            project_root=project_root,
            name="my-schedule",
            host="test-host",
            cron="0 * * * *",
            command="echo hi",
        )
        text = out.read_text()
        assert "Generated by `axi schedule`" in text
        assert "my-schedule" in text
        # Host doesn't appear inside the cron artifact body (it's encoded
        # via the deploy/<host>/ directory path); but the marker for
        # install-side idempotence must be present.
        assert "axi schedule managed: my-schedule" in text

    def test_overwrites_existing_artifact(self, project_root):
        """Re-running create with the same name overwrites the artifact —
        the user is updating the schedule definition."""
        from axiom.cli.schedule import create_schedule
        create_schedule(
            project_root=project_root,
            name="updateable",
            host="test-host",
            cron="0 0 * * *",
            command="echo old",
        )
        out = create_schedule(
            project_root=project_root,
            name="updateable",
            host="test-host",
            cron="0 12 * * *",
            command="echo new",
        )
        text = out.read_text()
        assert "echo new" in text
        assert "echo old" not in text
        assert "0 12 * * *" in text

    def test_per_host_isolation(self, project_root):
        """Same `name` for two hosts writes two separate files."""
        from axiom.cli.schedule import create_schedule
        a = create_schedule(
            project_root=project_root,
            name="same-name",
            host="test-host",
            cron="0 * * * *",
            command="echo a",
        )
        b = create_schedule(
            project_root=project_root,
            name="same-name",
            host="other",
            cron="0 * * * *",
            command="echo b",
        )
        assert a != b
        assert a.is_file() and b.is_file()


class TestValidation:
    @pytest.mark.parametrize("bad_name", ["", ".", "..", "with/slash", "with\\bs"])
    def test_name_validation(self, project_root, bad_name):
        from axiom.cli.schedule import create_schedule
        with pytest.raises(ValueError):
            create_schedule(
                project_root=project_root,
                name=bad_name,
                host="test-host",
                cron="0 * * * *",
                command="echo",
            )

    @pytest.mark.parametrize("bad_host", ["", ".", "..", "with/slash"])
    def test_host_validation(self, project_root, bad_host):
        from axiom.cli.schedule import create_schedule
        with pytest.raises(ValueError):
            create_schedule(
                project_root=project_root,
                name="ok-name",
                host=bad_host,
                cron="0 * * * *",
                command="echo",
            )

    def test_empty_cron_rejected(self, project_root):
        from axiom.cli.schedule import create_schedule
        with pytest.raises(ValueError):
            create_schedule(
                project_root=project_root,
                name="ok",
                host="test-host",
                cron="",
                command="echo",
            )

    def test_cron_wrong_field_count_rejected(self, project_root):
        """Cron is 5 fields (minute hour day month weekday) on standard
        crontabs. Reject obviously-malformed expressions early."""
        from axiom.cli.schedule import create_schedule
        with pytest.raises(ValueError):
            create_schedule(
                project_root=project_root,
                name="ok",
                host="test-host",
                cron="bogus",
                command="echo",
            )

    def test_empty_command_rejected(self, project_root):
        from axiom.cli.schedule import create_schedule
        with pytest.raises(ValueError):
            create_schedule(
                project_root=project_root,
                name="ok",
                host="test-host",
                cron="0 * * * *",
                command="",
            )


class TestListSchedules:
    def test_no_schedules_returns_empty(self, project_root):
        from axiom.cli.schedule import list_schedules
        assert list_schedules(project_root) == []

    def test_lists_created_schedules(self, project_root):
        from axiom.cli.schedule import create_schedule, list_schedules
        create_schedule(
            project_root=project_root, name="a", host="test-host",
            cron="0 * * * *", command="echo a",
        )
        create_schedule(
            project_root=project_root, name="b", host="test-host",
            cron="0 0 * * *", command="echo b",
        )
        listed = list_schedules(project_root)
        names = {s["name"] for s in listed}
        assert names == {"a", "b"}
