{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axiom-secrets.serviceAccountName" . }}
  labels:
    {{- include "axiom-secrets.labels" . | nindent 4 }}
    component: openbao
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
