# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Claude Code renderer.

Emits `.claude/commands/axi/<noun>/<verb>.md` shims. Each shim shells out to
the `axi` CLI, preserving exact CLI parity. Subdirectory nesting maps directly
onto Claude Code's slash-command namespace, so users get `/axi <noun> <verb>`.

For chat slash commands (the `/help`, `/permissions` family), emits
`.claude/commands/axi/chat/<command>.md` so they're addressable from the
Claude Code REPL too — wrapped to invoke `axi chat` if needed.
"""

from __future__ import annotations

from pathlib import Path

from ..discovery import CommandTree, Conflict, SlashCommand, Verb

_GENERATED_MARKER = "<!-- generated by `axi commands generate` — do not edit -->"


def _shim_body(noun: str, verb: Verb, conflicts: list[Conflict]) -> str:
    """Render the markdown body for a single CLI verb shim."""
    arg_placeholders = " ".join(f"${i}" for i in range(len(verb.args)))
    full_cmd = f"axi {noun} {verb.name} {arg_placeholders}".strip()

    front_lines = [
        "---",
        f"description: {verb.help or f'axi {noun} {verb.name}'}",
        f"allowed-tools: Bash(axi {noun} {verb.name} *)",
    ]
    if verb.args:
        front_lines.append(f"argument-hint: <{'> <'.join(verb.args)}>")
    front_lines.append("---")

    body = [
        *front_lines,
        "",
        _GENERATED_MARKER,
        "",
        f"Run the Axiom CLI verb `axi {noun} {verb.name}` with the supplied arguments.",
        "",
        f"!`{full_cmd}`",
        "",
    ]

    if conflicts:
        body.append("> **Conflict notes:**")
        for c in conflicts:
            body.append(
                f"> - `{c.key}` — winner: `{c.winner_extension}`; shadowed: "
                f"`{c.loser_extension}` ({c.reason})"
            )
        body.append("")

    return "\n".join(body)


def _slash_shim_body(slash: SlashCommand) -> str:
    """Render a markdown shim for a chat slash command.

    These wrap `axi chat --send-command` (or analogous), so that users who
    don't have a chat session open can still invoke them. If `axi chat`
    doesn't yet support that flag, the user runs the command as written.
    """
    front = [
        "---",
        f"description: {slash.description or f'/{slash.name} (chat)'}",
        "allowed-tools: Bash(axi chat *)",
        "---",
    ]
    body = [
        *front,
        "",
        _GENERATED_MARKER,
        "",
        f"Invoke the Axiom chat slash command `/{slash.name}`.",
        "",
        f"!`axi chat --send-command /{slash.name}`",
        "",
    ]
    return "\n".join(body)


def render(tree: CommandTree, out_dir: Path) -> list[Path]:
    """Materialize Claude Code shims under `out_dir/.claude/commands/axi/`.

    Returns the list of files written.
    """
    base = out_dir / ".claude" / "commands" / "axi"
    base.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # CLI noun-verb tree
    for noun, cli_noun in sorted(tree.nouns.items()):
        noun_conflicts = [c for c in tree.conflicts if c.key == noun]
        noun_dir = base / noun
        noun_dir.mkdir(parents=True, exist_ok=True)

        if not cli_noun.verbs:
            # Noun with no introspectable verbs — emit a single dispatcher
            verb = Verb(name="_default", help=cli_noun.description, args=("args",))
            path = noun_dir / "default.md"
            path.write_text(
                _shim_body(noun, verb, noun_conflicts), encoding="utf-8"
            )
            written.append(path)
            continue

        for verb in cli_noun.verbs:
            path = noun_dir / f"{verb.name}.md"
            path.write_text(
                _shim_body(noun, verb, noun_conflicts), encoding="utf-8"
            )
            written.append(path)

    # Chat slash commands
    chat_dir = base / "chat"
    chat_dir.mkdir(parents=True, exist_ok=True)
    for name, slash in sorted(tree.slash_commands.items()):
        path = chat_dir / f"{name}.md"
        path.write_text(_slash_shim_body(slash), encoding="utf-8")
        written.append(path)

    return written
