# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Codex (OpenAI) renderer.

As of May 2026 Codex doesn't expose a user-defined slash-command system,
but it does speak MCP. Our job here is small: register the Axiom MCP server
in Codex's MCP config so its tools become contextually invokable from the
Codex chat. Users invoke them via natural language ("init an ext named foo")
and Codex routes to the right MCP tool.

Codex MCP config lives at `~/.codex/config.toml`. We emit/update the
`[mcp_servers.axiom]` block (TOML-shape per the Codex CLI reference). Other
top-level keys are preserved.
"""

from __future__ import annotations

from pathlib import Path

from ..discovery import CommandTree


def _toml_block() -> str:
    """The Axiom MCP server block to inject."""
    return (
        "# Generated by `axi commands generate` — do not edit this block by hand.\n"
        '[mcp_servers.axiom]\n'
        'command = "axi"\n'
        'args = ["mcp", "serve"]\n'
    )


_BEGIN_MARKER = "# >>> axi commands generate (axiom) >>>"
_END_MARKER = "# <<< axi commands generate (axiom) <<<"


def render(tree: CommandTree, out_dir: Path) -> list[Path]:
    """Update `out_dir/.codex/config.toml` to include the Axiom MCP server.

    `tree` is currently unused (Codex has no per-tool shim surface), but is
    accepted for renderer-interface uniformity. Returns list of files written.
    """
    del tree  # interface uniformity; Codex doesn't surface per-verb shims
    config_dir = out_dir / ".codex"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"

    existing = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
    block = f"{_BEGIN_MARKER}\n{_toml_block()}{_END_MARKER}\n"

    if _BEGIN_MARKER in existing and _END_MARKER in existing:
        # Replace the existing block (idempotent regen)
        before, _, rest = existing.partition(_BEGIN_MARKER)
        _, _, after = rest.partition(_END_MARKER)
        # `after` starts with the trailing newline of the END marker line
        new_text = before + block + after.lstrip("\n")
    else:
        sep = "" if existing.endswith("\n") or not existing else "\n"
        new_text = existing + sep + ("\n" if existing else "") + block

    config_path.write_text(new_text, encoding="utf-8")
    return [config_path]
