# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Cursor renderer.

Cursor's namespace doesn't nest, so noun-verb collapses to flat slash names
joined by a hyphen: `axi hygiene list worktrees` → `/axi-tidy-worktrees`. We also emit
a `.cursor/mcp.json` that registers the Axiom MCP server so Cursor surfaces
the same operations contextually (its native UX) for users who prefer that.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..discovery import CommandTree

_GENERATED_MARKER = "<!-- generated by `axi commands generate` — do not edit -->"


def _flat_shim_body(noun: str, verb_name: str, help_text: str, args: tuple[str, ...]) -> str:
    arg_placeholders = " ".join(f"${i}" for i in range(len(args)))
    full_cmd = f"axi {noun} {verb_name} {arg_placeholders}".strip()
    front = [
        "---",
        f"description: {help_text or f'axi {noun} {verb_name}'}",
        "---",
    ]
    body = [
        *front,
        "",
        _GENERATED_MARKER,
        "",
        f"Run: `{full_cmd}`",
        "",
    ]
    return "\n".join(body)


def render(tree: CommandTree, out_dir: Path) -> list[Path]:
    """Materialize Cursor configs under `out_dir/.cursor/`.

    Writes:
      - `.cursor/mcp.json` — registers the Axiom MCP server so Cursor sees
        all tools natively (its preferred surface).
      - `.cursor/commands/axi-<noun>-<verb>.md` — flat shims for users who
        want explicit slash invocation.

    Returns list of files written.
    """
    base = out_dir / ".cursor"
    base.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # mcp.json — registers the Axiom MCP server
    mcp_json_path = base / "mcp.json"
    mcp_config = {
        "mcpServers": {
            "axiom": {
                "command": "axi",
                "args": ["mcp", "serve"],
                "env": {},
            }
        }
    }
    mcp_json_path.write_text(json.dumps(mcp_config, indent=2) + "\n", encoding="utf-8")
    written.append(mcp_json_path)

    # Flat command shims (no nesting in Cursor)
    cmd_dir = base / "commands"
    cmd_dir.mkdir(parents=True, exist_ok=True)
    for noun, cli_noun in sorted(tree.nouns.items()):
        if not cli_noun.verbs:
            path = cmd_dir / f"axi-{noun}.md"
            path.write_text(
                _flat_shim_body(noun, "", cli_noun.description, ("args",)),
                encoding="utf-8",
            )
            written.append(path)
            continue
        for verb in cli_noun.verbs:
            path = cmd_dir / f"axi-{noun}-{verb.name}.md"
            path.write_text(
                _flat_shim_body(noun, verb.name, verb.help, verb.args),
                encoding="utf-8",
            )
            written.append(path)

    return written
