# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Neovim renderer.

Emits a single Lua plugin file `lua/axi.lua` that registers a top-level
`:Axi` user command with subcommand routing. Users invoke as
`:Axi <noun> <verb> [args...]`. Tab-completion is wired so the noun-verb
tree is discoverable from the command line.

Drop the resulting file into `~/.config/nvim/lua/` and `require("axi")` from
your init.lua, or symlink it into a plugin manager's path.
"""

from __future__ import annotations

from pathlib import Path

from ..discovery import CommandTree


def _lua_table_lit(values: list[str]) -> str:
    parts = [f'"{v}"' for v in values]
    return "{ " + ", ".join(parts) + " }"


def render(tree: CommandTree, out_dir: Path) -> list[Path]:
    base = out_dir / ".axi" / "shims" / "neovim" / "lua"
    base.mkdir(parents=True, exist_ok=True)
    plugin_path = base / "axi.lua"

    nouns_lit = _lua_table_lit(sorted(tree.nouns.keys()))

    verbs_blocks = []
    for noun, cli_noun in sorted(tree.nouns.items()):
        if cli_noun.verbs:
            verbs_blocks.append(
                f'  ["{noun}"] = '
                + _lua_table_lit([v.name for v in cli_noun.verbs])
                + ","
            )
        else:
            verbs_blocks.append(f'  ["{noun}"] = {{}},')

    verbs_table = "local verbs = {\n" + "\n".join(verbs_blocks) + "\n}\n"

    body = f"""-- Generated by `axi commands generate` — do not edit.
-- :Axi <noun> <verb> [args...]
-- Tab-completion follows the installed-extensions noun/verb tree.

local M = {{}}
local nouns = {nouns_lit}
{verbs_table}
local function run(opts)
  local args = opts.fargs
  if #args == 0 then
    vim.notify("Usage: :Axi <noun> <verb> [args...]", vim.log.levels.WARN)
    return
  end
  local cmd = "axi " .. table.concat(args, " ")
  vim.cmd("!" .. cmd)
end

local function complete(arg_lead, cmd_line, _)
  local parts = vim.split(cmd_line, "%s+")
  -- parts[1] = "Axi", parts[2] = noun, parts[3] = verb
  if #parts <= 2 then
    return vim.tbl_filter(function(n) return vim.startswith(n, arg_lead) end, nouns)
  elseif #parts == 3 then
    local noun = parts[2]
    local vlist = verbs[noun] or {{}}
    return vim.tbl_filter(function(v) return vim.startswith(v, arg_lead) end, vlist)
  end
  return {{}}
end

vim.api.nvim_create_user_command("Axi", run, {{
  nargs = "+",
  complete = complete,
  desc = "Run an Axiom CLI verb (axi commands generate)",
}})

return M
"""
    plugin_path.write_text(body, encoding="utf-8")
    return [plugin_path]
