# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Vim renderer.

Emits `axi.vim` defining a top-level `:Axi` user command with a custom
completion function that walks the installed-extensions noun-verb tree.

Drop into `~/.vim/plugin/` (auto-loaded) or source manually from `.vimrc`.
"""

from __future__ import annotations

from pathlib import Path

from ..discovery import CommandTree


def render(tree: CommandTree, out_dir: Path) -> list[Path]:
    base = out_dir / ".axi" / "shims" / "vim" / "plugin"
    base.mkdir(parents=True, exist_ok=True)
    plugin_path = base / "axi.vim"

    nouns_lit = " ".join(sorted(tree.nouns.keys()))
    verb_dict_pairs: list[str] = []
    for noun, cli_noun in sorted(tree.nouns.items()):
        if cli_noun.verbs:
            v = " ".join(v.name for v in cli_noun.verbs)
        else:
            v = ""
        verb_dict_pairs.append(f"  \\ '{noun}': '{v}',")

    verb_dict = "let s:axi_verbs = {\n" + "\n".join(verb_dict_pairs) + "\n  \\ }\n"

    template = (
        '" Generated by `axi commands generate` — do not edit.\n'
        '" :Axi <noun> <verb> [args...]\n'
        "\n"
        "let s:axi_nouns = '__NOUNS__'\n"
        "__VERB_DICT__"
        "\n"
        "function! AxiRun(...) abort\n"
        "  if a:0 == 0\n"
        "    echohl WarningMsg | echomsg 'Usage: :Axi <noun> <verb> [args...]' | echohl None\n"
        "    return\n"
        "  endif\n"
        "  execute '!axi ' . join(a:000, ' ')\n"
        "endfunction\n"
        "\n"
        "function! AxiComplete(arg_lead, cmd_line, cursor_pos) abort\n"
        "  let parts = split(a:cmd_line, '\\s\\+')\n"
        '  " parts[0] = ''Axi'', parts[1] = noun, parts[2] = verb\n'
        "  if len(parts) <= 2\n"
        "    return filter(split(s:axi_nouns), 'v:val =~ \"^\" . a:arg_lead')\n"
        "  elseif len(parts) == 3\n"
        "    let noun = parts[1]\n"
        "    if has_key(s:axi_verbs, noun)\n"
        "      return filter(split(s:axi_verbs[noun]), 'v:val =~ \"^\" . a:arg_lead')\n"
        "    endif\n"
        "  endif\n"
        "  return []\n"
        "endfunction\n"
        "\n"
        "command! -nargs=+ -complete=customlist,AxiComplete Axi call AxiRun(<f-args>)\n"
    )
    body = template.replace("__NOUNS__", nouns_lit).replace("__VERB_DICT__", verb_dict)
    plugin_path.write_text(body, encoding="utf-8")
    return [plugin_path]
