# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0
"""``axi ext docs`` — render EXTENSION_CONTRACTS.md from an extension.

The output is a self-contained markdown description of the extension's
public contract, derived from three sources:

1. ``[[extension.provides]]`` blocks in ``axiom-extension.toml`` — the
   declared capabilities.
2. The package's ``__all__`` — the enforced public API surface.
3. ``skills/<name>/SKILL.md`` files — natural-language skill instructions.

This is useful both as living documentation inside the extension repo and
as paste-able context for AI assistants generating code against the
extension.
"""

from __future__ import annotations

import argparse
import ast
import tomllib
from pathlib import Path
from typing import Any

from axiom.cli.ext._output import console
from axiom.cli.ext.provider import CliContext

# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


def _load_manifest(ext_path: Path) -> dict[str, Any]:
    manifest = ext_path / "axiom-extension.toml"
    with manifest.open("rb") as fh:
        return tomllib.load(fh)


def _extract_all_names(init_path: Path) -> list[str]:
    """Return the list of strings declared in ``__all__`` or an empty list."""
    if not init_path.exists():
        return []
    try:
        tree = ast.parse(init_path.read_text(encoding="utf-8"))
    except SyntaxError:
        return []
    for node in ast.walk(tree):
        targets: list[ast.expr]
        value: ast.expr | None
        if isinstance(node, ast.Assign):
            targets = list(node.targets)
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target] if node.target else []
            value = node.value
        else:
            continue
        for t in targets:
            if isinstance(t, ast.Name) and t.id == "__all__" and value is not None:
                if isinstance(value, (ast.List, ast.Tuple)):
                    return [
                        el.value
                        for el in value.elts
                        if isinstance(el, ast.Constant) and isinstance(el.value, str)
                    ]
    return []


def _collect_skill_docs(ext_path: Path, pkg_name: str) -> list[tuple[str, str]]:
    """Return ``(skill_name, SKILL.md body)`` pairs for each skill directory."""
    skills_dir = ext_path / pkg_name / "skills"
    if not skills_dir.is_dir():
        return []
    out: list[tuple[str, str]] = []
    for child in sorted(skills_dir.iterdir()):
        if not child.is_dir():
            continue
        skill_md = child / "SKILL.md"
        if skill_md.exists():
            out.append((child.name, skill_md.read_text(encoding="utf-8")))
    return out


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render_contracts(ext_path: Path) -> str:
    """Render EXTENSION_CONTRACTS.md content for the extension at ``ext_path``."""
    manifest = _load_manifest(ext_path)
    ext_block = manifest.get("extension", {}) or {}
    name = ext_block.get("name") or ext_path.name
    version = ext_block.get("version", "unknown")
    description = ext_block.get("description", "")
    owner = ext_block.get("owner", "")
    license_id = ext_block.get("license", "")

    init_path = ext_path / name / "__init__.py"
    public_api = _extract_all_names(init_path)
    skills = _collect_skill_docs(ext_path, name)
    provides = ext_block.get("provides", []) or []
    consumes = ext_block.get("consumes", []) or []

    lines: list[str] = []
    lines.append(f"# {name} — Extension Contracts")
    lines.append("")
    lines.append(
        "_Generated by `axi ext docs`. Do not edit by hand — regenerate from the manifest._"
    )
    lines.append("")

    # -- Metadata -----------------------------------------------------------
    lines.append("## Metadata")
    lines.append("")
    lines.append(f"- **Name:** `{name}`")
    lines.append(f"- **Version:** `{version}`")
    if description:
        lines.append(f"- **Description:** {description}")
    if owner:
        lines.append(f"- **Owner:** {owner}")
    if license_id:
        lines.append(f"- **License:** {license_id}")
    aeos_version = ext_block.get("aeos_version")
    if aeos_version:
        lines.append(f"- **AEOS version:** {aeos_version}")
    lines.append("")

    # -- Capabilities (provides) -------------------------------------------
    lines.append("## Provided Capabilities")
    lines.append("")
    if not provides:
        lines.append("_No capabilities declared._")
        lines.append("")
    else:
        for block in provides:
            kind = block.get("kind", "unknown")
            label = (
                block.get("name")
                or block.get("noun")
                or block.get("integration")
                or ", ".join(block.get("events", []) or [])
                or ", ".join(block.get("names", []) or [])
                or "(unnamed)"
            )
            lines.append(f"### `{kind}`: {label}")
            lines.append("")
            if block.get("description"):
                lines.append(block["description"])
                lines.append("")
            # Pretty-print the remaining fields as a bullet list.
            for key in sorted(k for k in block if k not in {"kind", "description"}):
                value = block[key]
                lines.append(f"- **{key}:** `{value}`")
            lines.append("")

    # -- Public API ---------------------------------------------------------
    lines.append("## Public API")
    lines.append("")
    if public_api:
        lines.append(f"Importable from `{name}`:")
        lines.append("")
        for symbol in public_api:
            lines.append(f"- `{symbol}`")
        lines.append("")
    else:
        lines.append(f"_`{name}.__all__` is empty — no public symbols exported yet._")
        lines.append("")

    # -- Dependencies (consumes) -------------------------------------------
    if consumes:
        lines.append("## Consumed Dependencies")
        lines.append("")
        for block in consumes:
            kind = block.get("kind", "unknown")
            pkg = block.get("package", "(unnamed)")
            version_req = block.get("version", "")
            lines.append(f"- **{kind}** `{pkg}` {version_req}".rstrip())
        lines.append("")

    # -- Skills -------------------------------------------------------------
    if skills:
        lines.append("## Skills")
        lines.append("")
        for skill_name, body in skills:
            lines.append(f"### {skill_name}")
            lines.append("")
            lines.append(body.rstrip())
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Provider
# ---------------------------------------------------------------------------


class DocsProvider:
    """Built-in provider for ``axi ext docs [<path>]``."""

    verb = "docs"
    description = "Render EXTENSION_CONTRACTS.md from the manifest + public API + skills"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "path",
            nargs="?",
            default=None,
            help="Path to the extension (default: current working directory)",
        )
        parser.add_argument(
            "--stdout",
            action="store_true",
            help="Print to stdout instead of writing to <ext>/docs/EXTENSION_CONTRACTS.md",
        )

    def run(self, args: argparse.Namespace, context: CliContext) -> int:
        target = Path(args.path).resolve() if args.path else context.cwd
        manifest = target / "axiom-extension.toml"
        con = console()
        if not manifest.exists():
            con.print(
                f"axi ext docs: {target} does not look like an extension "
                "(no axiom-extension.toml); aborting"
            )
            return 1
        try:
            content = render_contracts(target)
        except Exception as exc:  # noqa: BLE001 — surface clearly
            con.print(f"axi ext docs: failed to render contracts: {exc}")
            return 1

        if args.stdout:
            con.print(content)
            return 0

        out_path = target / "docs" / "EXTENSION_CONTRACTS.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        con.print(f"axi ext docs: wrote {out_path}")
        return 0


__all__ = ["DocsProvider", "render_contracts"]
