# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""`CronBackend` — traditional Unix cron implementation (issue #205).

Production case for any Linux/Unix host using crontab(1). Idempotence
model: every managed entry carries a marker comment:

    */15 * * * * <command>  # axi schedule managed: <name>

Install reads `crontab -l`, filters lines matching the marker for
`<name>`, appends the new line, pipes the whole result back to
`crontab -`. Uninstall does the same with no append.
"""

from __future__ import annotations

from datetime import UTC, datetime

from .protocols import RemoteRunner

_MARKER_PREFIX = "# axi schedule managed: "


def _marker_for(schedule_name: str) -> str:
    return f"{_MARKER_PREFIX}{schedule_name}"


def _strip_managed_line(crontab: str, schedule_name: str) -> str:
    """Return `crontab` with any line containing the marker for
    `schedule_name` removed. Other lines preserved verbatim."""
    marker = _marker_for(schedule_name)
    kept: list[str] = []
    for line in crontab.splitlines():
        if marker in line:
            continue
        kept.append(line)
    out = "\n".join(kept)
    if crontab.endswith("\n") and out and not out.endswith("\n"):
        out += "\n"
    return out


def _current_crontab(runner: RemoteRunner) -> str:
    """Fetch the host user's current crontab. `crontab -l` returns
    rc=1 + "no crontab for ..." on stderr when none exists; treat
    that as an empty crontab, not an error."""
    result = runner.run(["crontab", "-l"])
    if result.returncode == 0:
        return result.stdout
    if "no crontab" in result.stderr.lower():
        return ""
    raise RuntimeError(
        f"crontab -l failed on {runner.host!r}: rc={result.returncode} "
        f"stderr={result.stderr!r}"
    )


def _apply_crontab(runner: RemoteRunner, new_crontab: str) -> None:
    """Pipe `new_crontab` to `crontab -` (atomic install)."""
    result = runner.run(["crontab", "-"], input=new_crontab)
    if not result.ok:
        raise RuntimeError(
            f"crontab - failed on {runner.host!r}: rc={result.returncode} "
            f"stderr={result.stderr!r}"
        )


class CronBackend:
    """SchedulerBackend impl for traditional Unix cron."""

    name: str = "cron"

    def artifact_filename(self, schedule_name: str) -> str:
        return f"{schedule_name}.cron"

    def render(self, *, schedule_name: str, cron: str, command: str) -> str:
        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        marker = _marker_for(schedule_name)
        return (
            f"# Generated by `axi schedule` on {timestamp}\n"
            f"# Schedule:  {schedule_name}\n"
            f"# Cron:      {cron}\n"
            f"# Backend:   cron\n"
            "#\n"
            "# Placeholders in <command> (e.g. ${REPO_DIR}) are substituted at\n"
            "# install time by `axi schedule install --host <host>`.\n"
            "\n"
            f"{cron} {command}  {marker}\n"
        )

    def install_artifact(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
        artifact_content: str,
    ) -> None:
        """Parse the rendered ``.cron`` artifact and install it.

        The orchestrator hands raw artifact bytes to the backend — the
        backend owns its own parsing format. CronBackend's artifact is
        a single managed cron line (plus provenance-comment header):

            */15 * * * * <command>  # axi schedule managed: <name>

        Parse out cron-expr + command, then route to :meth:`install`.
        """
        marker = _marker_for(schedule_name)
        for line in artifact_content.splitlines():
            if marker not in line:
                continue
            body = line.split(marker, 1)[0].rstrip()
            body = body.rstrip("#").rstrip()
            # First 5 whitespace-separated tokens = cron expression
            parts = body.split(None, 5)
            if len(parts) < 6:
                raise ValueError(
                    f"cron artifact for {schedule_name!r} has a managed line "
                    f"with fewer than 5 cron fields + command: {line!r}"
                )
            cron = " ".join(parts[:5])
            command = parts[5]
            self.install(
                runner=runner,
                schedule_name=schedule_name,
                cron=cron,
                command=command,
            )
            return
        raise ValueError(
            f"cron artifact for {schedule_name!r} has no managed line "
            f"with marker {marker!r}"
        )

    def install(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
        cron: str,
        command: str,
    ) -> None:
        current = _current_crontab(runner)
        cleaned = _strip_managed_line(current, schedule_name)
        marker = _marker_for(schedule_name)
        new_line = f"{cron} {command}  {marker}\n"
        if cleaned and not cleaned.endswith("\n"):
            cleaned += "\n"
        new_crontab = cleaned + new_line
        _apply_crontab(runner, new_crontab)

    def uninstall(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
    ) -> None:
        try:
            current = _current_crontab(runner)
        except RuntimeError:
            raise
        if not current:
            return
        cleaned = _strip_managed_line(current, schedule_name)
        if cleaned == current:
            _apply_crontab(runner, current)
            return
        _apply_crontab(runner, cleaned)
