# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""`SystemdTimerBackend` — modern Linux scheduler impl via systemd-timer
(issue #205, slice 10).

Modern Linux distributions prefer user-level systemd timers over
crontab. Two unit files per schedule: a `.service` (what to run) and a
`.timer` (when to run). Files live in `~/.config/systemd/user/` and are
managed via `systemctl --user enable --now <name>.timer`.

The artifact format is a *single* file bundling both unit bodies with
sentinel delimiters:

    === service ===
    [Unit]
    ...
    === timer ===
    [Unit]
    ...

This keeps the `deploy/<host>/<name>.<ext>` discovery pattern intact
(one artifact file per schedule) while still being human-readable.

Cron → systemd OnCalendar translation is more forgiving than launchd's
StartCalendarInterval — systemd's calendar grammar natively supports
steps, ranges (`9..17`), and lists (`9,12,15`).

User-level timers require `loginctl enable-linger <user>` to survive
logout. That's out of scope for the backend — document it as a host
prerequisite.
"""

from __future__ import annotations

from datetime import UTC, datetime

from .protocols import RemoteRunner

_SECTION_SERVICE = "=== service ==="
_SECTION_TIMER = "=== timer ==="

_DISABLE_TOLERATED_PATTERNS = (
    "does not exist",
    "no such file",
    "not loaded",
    "unit file ",
    "no installation",
)


# ---------------------------------------------------------------------------
# Cron → systemd OnCalendar
# ---------------------------------------------------------------------------


def _translate_field(raw: str, *, pad_zero: bool = False) -> str:
    """Convert one cron field to its systemd OnCalendar equivalent.

    Rules:
      `*`           → `*`
      `0`           → `00` (when pad_zero=True; matches HH:MM:SS convention)
      `15`          → `15`
      `*/N`         → `0/N` (explicit start; cron's `*/N` ≡ `0/N` for time fields)
      `9-17`        → `9..17`
      `9,12,15`     → `9,12,15`
      mixed (e.g. `1-5,8` or `*/15-30`) → ValueError
    """
    if "," in raw and ("-" in raw or "/" in raw):
        raise ValueError(f"mixed cron syntax not supported: {raw!r}")
    if raw.startswith("*/"):
        return f"0/{raw[2:]}"
    if "-" in raw:
        a, b = raw.split("-", 1)
        return f"{a}..{b}"
    if pad_zero and raw == "0":
        return "00"
    return raw


def _cron_to_oncalendar(cron: str) -> str:
    """Translate a cron expression to a systemd OnCalendar spec.

    Macros pass through to systemd's native ones (`@daily` → `daily`).
    """
    cron = cron.strip()
    macro_map = {
        "@hourly": "hourly",
        "@daily": "daily",
        "@midnight": "daily",
        "@weekly": "weekly",
        "@monthly": "monthly",
        "@yearly": "yearly",
        "@annually": "yearly",
    }
    if cron in macro_map:
        return macro_map[cron]
    if cron.startswith("@"):
        raise ValueError(f"unsupported cron macro for systemd: {cron!r}")

    fields = cron.split()
    if len(fields) != 5:
        raise ValueError(
            f"cron expression must have 5 fields, got {len(fields)}: {cron!r}"
        )
    raw_minute, raw_hour, raw_day, raw_month, raw_weekday = fields
    minute = _translate_field(raw_minute, pad_zero=True)
    hour = _translate_field(raw_hour, pad_zero=False)
    day = _translate_field(raw_day, pad_zero=False)
    month = _translate_field(raw_month, pad_zero=False)
    weekday = _translate_field(raw_weekday, pad_zero=False)

    # Build "DayOfWeek Year-Month-Day Hour:Minute:Second"
    # When weekday is `*`, omit it.
    date_part = f"*-{month}-{day}"
    time_part = f"{hour}:{minute}:00"
    if weekday == "*":
        return f"{date_part} {time_part}"
    return f"{_weekday_for_systemd(weekday)} {date_part} {time_part}"


def _weekday_for_systemd(weekday: str) -> str:
    """Map cron numeric weekdays (0=Sunday..6=Saturday) to systemd names
    where the field is a single digit. Pass through more complex specs
    (`Mon..Fri`) verbatim — the caller may have supplied a systemd-native
    weekday name already."""
    numeric = {
        "0": "Sun", "1": "Mon", "2": "Tue", "3": "Wed",
        "4": "Thu", "5": "Fri", "6": "Sat", "7": "Sun",
    }
    return numeric.get(weekday, weekday)


# ---------------------------------------------------------------------------
# Unit file emission
# ---------------------------------------------------------------------------


def _emit_service_unit(*, schedule_name: str, command: str, generated_at: str) -> str:
    return (
        f"# Generated by `axi schedule` on {generated_at}\n"
        f"# Schedule: {schedule_name}\n"
        "[Unit]\n"
        f"Description=axi schedule: {schedule_name}\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"ExecStart=/bin/sh -c '{command}'\n"
    )


def _emit_timer_unit(*, schedule_name: str, oncalendar: str, generated_at: str) -> str:
    return (
        f"# Generated by `axi schedule` on {generated_at}\n"
        f"# Schedule: {schedule_name}\n"
        "[Unit]\n"
        f"Description=axi schedule timer: {schedule_name}\n"
        "\n"
        "[Timer]\n"
        f"OnCalendar={oncalendar}\n"
        "Persistent=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


# ---------------------------------------------------------------------------
# Artifact bundle (service + timer in one file)
# ---------------------------------------------------------------------------


def _bundle_artifact(*, service_body: str, timer_body: str) -> str:
    return (
        f"{_SECTION_SERVICE}\n"
        f"{service_body}"
        f"{_SECTION_TIMER}\n"
        f"{timer_body}"
    )


def _parse_artifact(content: str) -> tuple[str, str]:
    """Return `(service_body, timer_body)` from a bundled artifact."""
    if _SECTION_SERVICE not in content or _SECTION_TIMER not in content:
        raise ValueError(
            f"systemd artifact missing required section markers "
            f"({_SECTION_SERVICE!r} / {_SECTION_TIMER!r})"
        )
    _, after_service = content.split(_SECTION_SERVICE, 1)
    service_body, timer_body = after_service.split(_SECTION_TIMER, 1)
    # Trim the leading newline that follows the marker line itself.
    return service_body.lstrip("\n"), timer_body.lstrip("\n")


# ---------------------------------------------------------------------------
# Runner helpers
# ---------------------------------------------------------------------------


def _resolve_user_dir(runner: RemoteRunner) -> str:
    """Resolve `${AXIOM_SYSTEMD_USER_DIR:-$HOME/.config/systemd/user}`.

    Passed as a *string* (not argv) so SSHRunner sends it to the remote
    shell unchanged; argv form gets re-flattened by ssh and breaks the
    `sh -c '...'` quoting.
    """
    result = runner.run(
        'echo "${AXIOM_SYSTEMD_USER_DIR:-$HOME/.config/systemd/user}"'
    )
    if not result.ok:
        raise RuntimeError(
            f"could not resolve systemd user dir on {runner.host!r}: "
            f"rc={result.returncode} stderr={result.stderr!r}"
        )
    return result.stdout.strip().rstrip("/")


def _daemon_reload(runner: RemoteRunner) -> None:
    result = runner.run(["systemctl", "--user", "daemon-reload"])
    if not result.ok:
        raise RuntimeError(
            f"systemctl --user daemon-reload failed on {runner.host!r}: "
            f"rc={result.returncode} stderr={result.stderr!r}"
        )


def _enable_now(runner: RemoteRunner, timer_unit: str) -> None:
    result = runner.run(["systemctl", "--user", "enable", "--now", timer_unit])
    if not result.ok:
        raise RuntimeError(
            f"systemctl --user enable --now {timer_unit!r} failed on "
            f"{runner.host!r}: rc={result.returncode} stderr={result.stderr!r}"
        )


def _disable_now(runner: RemoteRunner, timer_unit: str) -> None:
    """Disable + stop the timer. Tolerate the not-loaded case so
    `uninstall` on a missing schedule is a clean no-op."""
    result = runner.run(["systemctl", "--user", "disable", "--now", timer_unit])
    if result.ok:
        return
    msg = (result.stderr + result.stdout).lower()
    if any(p in msg for p in _DISABLE_TOLERATED_PATTERNS):
        return
    raise RuntimeError(
        f"systemctl --user disable --now {timer_unit!r} failed on "
        f"{runner.host!r}: rc={result.returncode} stderr={result.stderr!r}"
    )


# ---------------------------------------------------------------------------
# Backend
# ---------------------------------------------------------------------------


class SystemdTimerBackend:
    """SchedulerBackend impl for systemd --user timers."""

    name: str = "systemd"

    def artifact_filename(self, schedule_name: str) -> str:
        return f"{schedule_name}.systemd"

    def render(self, *, schedule_name: str, cron: str, command: str) -> str:
        oncalendar = _cron_to_oncalendar(cron)
        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        service_body = _emit_service_unit(
            schedule_name=schedule_name, command=command, generated_at=timestamp,
        )
        timer_body = _emit_timer_unit(
            schedule_name=schedule_name, oncalendar=oncalendar, generated_at=timestamp,
        )
        return _bundle_artifact(service_body=service_body, timer_body=timer_body)

    def install_artifact(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
        artifact_content: str,
    ) -> None:
        service_body, timer_body = _parse_artifact(artifact_content)
        user_dir = _resolve_user_dir(runner)
        service_path = f"{user_dir}/{schedule_name}.service"
        timer_path = f"{user_dir}/{schedule_name}.timer"

        runner.write_file(service_path, service_body)
        runner.write_file(timer_path, timer_body)
        _daemon_reload(runner)
        _enable_now(runner, f"{schedule_name}.timer")

    def install(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
        cron: str,
        command: str,
    ) -> None:
        artifact = self.render(
            schedule_name=schedule_name, cron=cron, command=command,
        )
        self.install_artifact(
            runner=runner,
            schedule_name=schedule_name,
            artifact_content=artifact,
        )

    def uninstall(
        self,
        *,
        runner: RemoteRunner,
        schedule_name: str,
    ) -> None:
        user_dir = _resolve_user_dir(runner)
        timer_unit = f"{schedule_name}.timer"
        _disable_now(runner, timer_unit)
        runner.run([
            "rm", "-f",
            f"{user_dir}/{schedule_name}.service",
            f"{user_dir}/{schedule_name}.timer",
        ])
        _daemon_reload(runner)
