apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axi-presence.slug" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: axi-presence
    axiom.ai/owner: {{ include "axi-presence.slug" . }}
