# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Generators — render the canonical ``AGENTS.md`` into per-tool context files.

Per ADR-051, ``AGENTS.md`` is the single hand-authored project-context file.
The assistants that do *not* read it natively each get a **generated** file:

  * Cursor   → ``.cursor/rules/axiom.mdc``           (MDC: frontmatter + body)
  * Junie    → ``.junie/guidelines.md``               (plain markdown)
  * Copilot  → ``.github/copilot-instructions.md``    (plain markdown)

Every generated file opens with a DO-NOT-EDIT marker so a human knows to edit
``AGENTS.md`` instead, and so the drift check (``axi context check``) has a
stable signal. Rendering is a **pure function** of the canonical text, which
is what makes drift detection a simple string compare.

Adding a new tool = appending one :class:`Target` to :data:`TARGETS`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

__all__ = ["GENERATED_MARKER", "Target", "TARGETS"]

GENERATED_MARKER = "GENERATED by `axi context sync` from AGENTS.md — DO NOT EDIT"

_HEADER_COMMENT = (
    f"<!-- {GENERATED_MARKER}.\n"
    "     Edit AGENTS.md and re-run `axi context sync`. -->\n"
)

# Cursor MDC frontmatter: apply this rule to every request in the workspace.
_CURSOR_FRONTMATTER = (
    "---\n"
    "description: Project context (generated from AGENTS.md)\n"
    "alwaysApply: true\n"
    "---\n"
)


def _body(agents_md: str) -> str:
    """Canonical body, normalized to a single trailing newline."""
    return agents_md.strip() + "\n"


def _render_markdown(agents_md: str) -> str:
    """Plain-markdown target: DO-NOT-EDIT comment, then the canonical body."""
    return _HEADER_COMMENT + "\n" + _body(agents_md)


def _render_cursor(agents_md: str) -> str:
    """Cursor MDC target: frontmatter, DO-NOT-EDIT comment, then the body."""
    return _CURSOR_FRONTMATTER + _HEADER_COMMENT + "\n" + _body(agents_md)


@dataclass(frozen=True)
class Target:
    """One generated context file: where it goes and how to render it."""

    name: str  # short id: "cursor" | "junie" | "copilot"
    relpath: str  # posix path relative to the repo root
    render: Callable[[str], str]  # pure: canonical AGENTS.md text -> file contents


TARGETS: list[Target] = [
    Target("cursor", ".cursor/rules/axiom.mdc", _render_cursor),
    Target("junie", ".junie/guidelines.md", _render_markdown),
    Target("copilot", ".github/copilot-instructions.md", _render_markdown),
]
