# Copyright (c) 2026 The University of Texas at Austin
# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Proof, by independent method — not by self-consistency.

Anything can be made to agree with itself. These tests check the affine
form against two references it shares no code with:

1. **GUM's closed form.** JCGM 100:2008 §5, the law of propagation of
   uncertainty, including the covariance term, evaluated by hand on the
   declared structure.
2. **Monte Carlo.** JCGM 101 (GUM Supplement 1): draw from the joint
   distribution the symbols describe, push the samples through the same
   arithmetic numerically, and compare the sample standard deviation.

If the algebra were wrong, agreeing with a hand-written covariance sum AND
with sampling from a correlated multivariate normal would take a
conspiracy. Property-based tests then assert the structural laws — closure,
commutativity, associativity, and the bracket — over generated inputs
rather than chosen ones.

Seeds are fixed. A proof that passes intermittently is not a proof.
"""

from __future__ import annotations

import math

import numpy as np
import pytest
from hypothesis import assume, given, settings
from hypothesis import strategies as st

from axiom.uncertainty import (
    MagnitudeOnly,
    Quantity,
    add,
    correlation,
    difference,
    mean,
    product,
)

RNG = np.random.default_rng(20260928)
DRAWS = 400_000


def _sample(quantities: list[Quantity], draws: int = DRAWS) -> np.ndarray:
    """Draw each quantity from the joint distribution its symbols imply.

    Every symbol is an independent unit-variance source, so the joint
    structure is generated by sampling the SOURCES once and forming each
    quantity as its own linear combination. Correlation between quantities
    is therefore produced by construction — exactly the physical claim the
    affine form encodes, tested by realising it rather than restating it.
    """
    symbols = sorted({s for q in quantities for s in q.terms})
    eps = RNG.standard_normal((len(symbols), draws))
    index = {s: i for i, s in enumerate(symbols)}
    out = []
    for q in quantities:
        col = np.full(draws, q.value, dtype=float)
        for s, a in q.terms.items():
            col = col + a * eps[index[s]]
        out.append(col)
    return np.array(out)


def _gum_combined(quantities: list[Quantity]) -> float:
    """GUM §5 for a sum, written out longhand with the covariance term.

    u_c² = Σ u(xᵢ)² + 2 ΣΣ_{i<j} u(xᵢ) u(xⱼ) r(xᵢ, xⱼ)

    Deliberately implemented from the standard's formula using only `.u`
    and `correlation`, so it exercises the public surface the way an
    analyst would rather than reusing the internals under test.
    """
    total = sum(q.u**2 for q in quantities)
    for i, a in enumerate(quantities):
        for b in quantities[i + 1 :]:
            total += 2 * a.u * b.u * correlation(a, b)
    return math.sqrt(max(0.0, total))


BATH = "signals:bath:offset"
A_REP = "signals:tc-a:repeatability"
B_REP = "signals:tc-b:repeatability"
C_REP = "signals:tc-c:repeatability"


def _tcs() -> list[Quantity]:
    """Three thermocouples on one bath — correlated by construction."""
    return [
        Quantity(30.0, "degC", {BATH: 0.5, A_REP: 0.12}),
        Quantity(31.0, "degC", {BATH: 0.5, B_REP: 0.08}),
        Quantity(29.5, "degC", {BATH: 0.5, C_REP: 0.20}),
    ]


# --- 1. Agreement with GUM's closed form -------------------------------


def test_a_sum_matches_gums_law_of_propagation_including_covariance():
    qs = _tcs()
    assert add(qs).low == pytest.approx(_gum_combined(qs), rel=1e-12)


def test_a_difference_matches_gum_with_the_covariance_term_negative():
    a, b = _tcs()[0], _tcs()[1]
    d = difference(a, b)
    by_gum = math.sqrt(a.u**2 + b.u**2 - 2 * a.u * b.u * correlation(a, b))
    assert d.u == pytest.approx(by_gum, rel=1e-12)
    # and the shared systematic really does make the difference tighter
    assert d.u < math.sqrt(a.u**2 + b.u**2)


def test_a_mean_matches_gum_scaled_by_one_over_n():
    qs = _tcs()
    assert mean(qs).low == pytest.approx(_gum_combined(qs) / len(qs), rel=1e-12)


# --- 2. Agreement with Monte Carlo (GUM-S1) ----------------------------


def test_a_correlated_sum_matches_monte_carlo():
    qs = _tcs()
    drawn = _sample(qs).sum(axis=0)
    assert add(qs).low == pytest.approx(float(drawn.std(ddof=1)), rel=0.01)


def test_a_correlated_mean_matches_monte_carlo():
    qs = _tcs()
    drawn = _sample(qs).mean(axis=0)
    assert mean(qs).low == pytest.approx(float(drawn.std(ddof=1)), rel=0.01)


def test_a_difference_matches_monte_carlo_with_the_systematic_cancelling():
    a, b = _tcs()[0], _tcs()[1]
    drawn = _sample([a, b])
    assert difference(a, b).u == pytest.approx(float((drawn[0] - drawn[1]).std(ddof=1)), rel=0.01)


def test_forty_readings_on_one_bath_match_monte_carlo_and_do_NOT_average_the_offset_away():
    """The costliest available mistake, checked against sampling.

    Treating these as independent would claim 0.5/√40 ≈ 0.079. The truth is
    ~0.5, because the offset is common. Monte Carlo agrees with the affine
    form and disagrees with the naive answer by more than a factor of six.
    """
    qs = [
        Quantity(30.0, "degC", {BATH: 0.5, f"signals:tc-{i}:repeatability": 0.1}) for i in range(40)
    ]
    drawn = _sample(qs, draws=200_000).mean(axis=0)
    truth = float(drawn.std(ddof=1))
    assert mean(qs).low == pytest.approx(truth, rel=0.02)
    assert truth > 6 * (0.5 / math.sqrt(40))


def test_the_product_linearisation_is_accurate_where_it_claims_to_be():
    """Affine arithmetic is first-order. Where relative uncertainties are
    small the residual symbol keeps it honest; this checks the claim rather
    than assuming it."""
    a = Quantity(2.0, "m", {"signals:len:cal": 0.02})
    b = Quantity(3.0, "m", {"signals:wid:cal": 0.03})
    p = product(a, b, residual_symbol="data_platform:product:residual")
    drawn = _sample([a, b])
    truth = float((drawn[0] * drawn[1]).std(ddof=1))
    assert p.u == pytest.approx(truth, rel=0.02)


# --- 3. Structural laws, over generated inputs -------------------------

_coeff = st.floats(min_value=-5.0, max_value=5.0, allow_nan=False, allow_infinity=False)
_sym = st.sampled_from([BATH, A_REP, B_REP, C_REP, "signals:d:noise"])


@st.composite
def _quantity(draw) -> Quantity:
    terms = draw(st.dictionaries(_sym, _coeff, max_size=4))
    value = draw(st.floats(min_value=-1e4, max_value=1e4, allow_nan=False))
    return Quantity(value=value, unit="degC", terms=terms)


@settings(max_examples=250, deadline=None)
@given(st.lists(_quantity(), min_size=1, max_size=6))
def test_addition_is_commutative_and_associative(qs):
    """Closure, as a law rather than an example. Regrouping or reordering a
    combination cannot change it, which is what lets it nest without end."""
    whole = add(qs)
    assert add(list(reversed(qs))).low == pytest.approx(whole.low, abs=1e-9)
    if len(qs) >= 2:
        left = add(qs[:1])
        rest = add(qs[1:])
        regrouped = add(
            [
                Quantity(left.value, "degC", dict(left.terms)),
                Quantity(rest.value, "degC", dict(rest.terms)),
            ]
        )
        assert regrouped.low == pytest.approx(whole.low, abs=1e-9)
        assert regrouped.value == pytest.approx(whole.value, rel=1e-9, abs=1e-6)


@settings(max_examples=250, deadline=None)
@given(_quantity(), _quantity())
def test_correlation_is_always_a_valid_coefficient(a, b):
    r = correlation(a, b)
    assert -1.0 - 1e-9 <= r <= 1.0 + 1e-9


@settings(max_examples=200, deadline=None)
@given(_quantity())
def test_a_quantity_is_perfectly_correlated_with_itself(q):
    assume(q.u > 1e-9)
    assert correlation(q, q) == pytest.approx(1.0, abs=1e-9)


@settings(max_examples=200, deadline=None)
@given(_quantity(), st.floats(min_value=1e-6, max_value=1e6, allow_nan=False))
def test_scaling_preserves_relative_uncertainty(q, factor):
    assume(abs(q.value) > 1e-6 and q.u > 1e-12)
    scaled = q.scaled(factor)
    assert scaled.u / abs(scaled.value) == pytest.approx(q.u / abs(q.value), rel=1e-9)


# --- 4. The bracket, proved against arbitrary correlation --------------


@settings(max_examples=300, deadline=None)
@given(
    st.lists(
        st.floats(min_value=0.0, max_value=10.0, allow_nan=False, allow_infinity=False),
        min_size=2,
        max_size=5,
    )
)
def test_high_is_unconditional_and_low_unconstrained_is_a_true_floor(mags):
    """The mathematically complete claims, over any correlation at all.

    For magnitudes uᵢ combined under ANY correlation structure, the
    achievable standard deviation of the sum lies in
    [max(0, 2·max(uᵢ) − Σuᵢ), Σuᵢ]. Both endpoints are attainable, so
    neither can be tightened without an assumption.
    """
    got = add([MagnitudeOnly(0.0, "degC", m) for m in mags])
    total = sum(mags)
    assert got.high == pytest.approx(total, rel=1e-9)
    assert got.low_unconstrained == pytest.approx(max(0.0, 2 * max(mags) - total), rel=1e-9)
    assert got.low_unconstrained <= got.low + 1e-9 <= got.high + 1e-9


def test_the_headline_low_holds_only_under_its_stated_premise():
    """And the premise is named rather than buried: two equal magnitudes at
    r = −1 cancel exactly, which is BELOW the root-sum-square floor. That is
    not a defect in the bound; it is the reason the bound states a premise
    and carries the unconstrained floor beside it."""
    got = add([MagnitudeOnly(0.0, "degC", 0.4), MagnitudeOnly(0.0, "degC", 0.4)])
    assert got.low == pytest.approx(math.sqrt(2) * 0.4)  # r = 0
    assert got.low_unconstrained == pytest.approx(0.0)  # r = −1 is reachable
    assert got.high == pytest.approx(0.8)  # r = +1
    assert "non-negatively correlated" in got.premise
    assert "assumes" in got.reads()


@settings(max_examples=200, deadline=None)
@given(st.lists(st.floats(min_value=0.01, max_value=5.0, allow_nan=False), min_size=2, max_size=4))
def test_monte_carlo_never_escapes_the_unconditional_bracket(mags):
    """Sampling under any correlation we can construct stays inside.

    The tolerance is derived, not tuned. A sample standard deviation from
    ``n`` draws has relative standard error ≈ ``1/√(2(n−1))``; at 20,000
    draws that is 0.5%, so a 2% band is four standard errors. Asserting a
    sampled quantity to 1e-6 is not rigour, it is a test that fails on
    arithmetic noise — which is exactly what this one did first.
    """
    draws = 20_000
    tol = 4 / math.sqrt(2 * (draws - 1))
    n = len(mags)
    base = RNG.standard_normal((n, draws))
    shared = RNG.standard_normal(draws)
    for rho in (0.0, 0.5, 0.95):
        cols = [
            m * (math.sqrt(1 - rho) * base[i] + math.sqrt(rho) * shared) for i, m in enumerate(mags)
        ]
        truth = float(np.sum(cols, axis=0).std(ddof=1))
        got = add([MagnitudeOnly(0.0, "degC", m) for m in mags])
        assert got.low_unconstrained * (1 - tol) - 1e-9 <= truth <= got.high * (1 + tol) + 1e-9


class TestTheNumericsHoldAtTheExtremes:
    """Proven primitives beat hand-rolled ones, and the difference is measurable.

    Everything here was found by checking the extremes deliberately. The
    property tests in this file draw ordinary magnitudes and passed the whole
    time, which is the point: a formula that agrees with itself over the range
    you happened to sample is not the same as a correct implementation.
    """

    EXTREMES = (1e-200, 1e-8, 0.5, 1e8, 1e200)

    @pytest.mark.parametrize("c", EXTREMES)
    def test_a_quantity_knows_its_own_magnitude_at_any_scale(self, c):
        """`math.hypot`, not `sqrt(sum of squares)`.

        The hand-rolled form returns inf near 1e200 and 0.0 near 1e-200. So
        does `np.linalg.norm`, which is why the fix was the stdlib primitive
        rather than the array library — measured, not assumed.
        """
        q = Quantity(value=0.0, unit="degC", terms={"e:a:t": c, "e:b:t": c})
        assert math.isfinite(q.u)
        assert q.u > 0
        assert q.u == pytest.approx(c * math.sqrt(2))

    @pytest.mark.parametrize("c", EXTREMES)
    def test_self_correlation_is_exactly_one_at_any_scale(self, c):
        """The trap that a plausible 0.0 hides.

        Dividing a finished dot product by `ua * ub` underflows the numerator
        near 1e-200 and overflows it near 1e200, returning 0.0 for quantities
        that are perfectly correlated — a confident answer that is exactly
        wrong. Normalising each coefficient first keeps every product in
        [-1, 1].
        """
        q = Quantity(value=0.0, unit="degC", terms={"e:a:t": c, "e:b:t": c})
        assert correlation(q, q) == pytest.approx(1.0)

    @pytest.mark.parametrize("c", EXTREMES)
    def test_disjoint_sources_are_uncorrelated_at_any_scale(self, c):
        a = Quantity(value=0.0, unit="degC", terms={"e:a:t": c})
        b = Quantity(value=0.0, unit="degC", terms={"e:b:t": c})
        assert correlation(a, b) == pytest.approx(0.0)

    @pytest.mark.parametrize("c", EXTREMES)
    def test_a_shared_systematic_still_cancels_at_any_scale(self, c):
        a = Quantity(value=1.0, unit="degC", terms={"e:bath:offset": c})
        b = Quantity(value=0.0, unit="degC", terms={"e:bath:offset": c})
        assert difference(a, b).u == pytest.approx(0.0, abs=c * 1e-12)

    def test_the_denominator_can_vanish_while_neither_factor_does(self):
        """Why the two-step division was not enough either.

        `ua * ub` is 0.0 for magnitudes around 1e-200 even though both are
        representable. Dividing in two steps fixes the denominator and leaves
        the numerator broken, which is how the first fix passed the suite
        while still returning 0.0 for a perfect correlation.
        """
        u = 1e-200 * math.sqrt(2)
        assert u > 0
        assert u * u == 0.0  # the product is not representable

    def test_a_long_term_list_stays_inside_the_valid_range(self):
        """`fsum` is correctly rounded, so accumulated rounding cannot push a
        correlation past ±1 and force a clamp to do real work."""
        terms = {f"e:s{i}:t": 1.0 + i * 1e-9 for i in range(5000)}
        q = Quantity(value=0.0, unit="degC", terms=terms)
        assert correlation(q, q) == pytest.approx(1.0)
        assert -1.0 <= correlation(q, q) <= 1.0

    def test_the_parity_residual_is_the_sample_standard_deviation(self):
        """`statistics.stdev` IS the residual RMS about the mean.

        Computing `sqrt(sum((r - mean)^2) / (n - 1))` by hand was
        reimplementing it with worse accuracy, since `statistics` is
        fsum-based and correctly rounded.
        """
        import statistics

        from axiom.uncertainty.pipeline import from_parity

        predicted = [10.0, 12.0, 9.0, 11.0, 13.0, 8.5]
        observed = [10.2, 11.5, 9.4, 10.6, 12.9, 9.0]
        parity = from_parity(predicted, observed)
        residuals = [p - o for p, o in zip(predicted, observed, strict=True)]

        assert parity.bias == pytest.approx(statistics.fmean(residuals))
        assert parity.residual_rms == pytest.approx(statistics.stdev(residuals))
